Add schema validator and Publisher updated env config.
ONSdigital/eq-compose pull request #11
Opened 2018-02-07 08:51 UTC by samiwel

### Description
This PR adds the eq-schema-validator service to the eQ docker compose configuration. It also updates Publisher environment variables to reflect recent change to Publisher.

### How to test
Spin up the containers from the docker-compose configuration and check that you can author a simple questionnaire and preview in survey runner.

### Dependencies
This PR depends on a change to Publisher being merged first. https://github.com/ONSdigital/eq-publisher/pull/45

2018-02-07 08:54 UTC, samiwel commented
![](https://github.trello.services/images/mini-trello-icon.png) [Use schema-validator in eq-publisher (3)](https://trello.com/c/rLjImix1/368-use-schema-validator-in-eq-publisher-3)

2018-02-07 10:01 UTC, jonnyshaw89 requested changes

2018-02-07 10:01 UTC, jonnyshaw89 commented on eq.yml
> +    restart: on-failure
we should make this `always` just to be consistent

2018-02-08 09:33 UTC, jonnyshaw89 approved these changes

2018-02-12 13:29 UTC, merged